#!/bin/bash
set -e  # Stop the script if any command fails

# ─────────────────────────────────────────────────────────────────────────────
# activate-ied.sh
#
# Description: Activates an Industrial Edge Device (IED) using the onboarding
#              file generated by create-ied.sh
#
# Prerequisites:
#   - create-ied.sh must have been executed successfully first
#   - The onboarding file (device.txt) must exist at ./onboarding-file/device.txt
#
# Usage: sh activate-ied.sh
# ─────────────────────────────────────────────────────────────────────────────

# ─── Load Configuration ─────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo "❌ ERROR: Configuration file not found: $ENV_FILE"
  echo "   Copy .env.example to .env and fill in your values."
  exit 1
fi
set -a
# shellcheck source=.env
. "$ENV_FILE"
set +a

# ─── Project Variables ───────────────────────────────────────────────────────
ONBOARDING_FILE="$SCRIPT_DIR/onboarding-file/device.txt"

# ─── Validate Onboarding File Exists ─────────────────────────────────────────
if [ ! -f "$ONBOARDING_FILE" ]; then
  echo "❌ ERROR: Onboarding file not found at: $ONBOARDING_FILE"
  echo "   Please run create-ied.sh first."
  exit 1
fi

echo "✅ Onboarding file found: $ONBOARDING_FILE"

# ─── Step 1: Register IED Configuration ──────────────────────────────────────
echo "⚙️  Registering IED configuration..."

iectl config add ied \
  --name "device-config-dev" \
  --url "$DEVICE_URL" \
  --user "$DEVICE_USER" \
  --password "$DEVICE_PASSWORD"

echo "✅ IED configuration registered successfully."

# ─── Step 2: Activate IED ────────────────────────────────────────────────────
echo "🚀 Activating IED..."

iectl ied system activate \
  --files "$ONBOARDING_FILE"

echo "✅ IED activated successfully!"